name: alcohol_collection
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # for firebase
  firebase_core: ^0.7.0
  firebase_storage: ^7.0.0
  cloud_firestore: "^0.16.0+1"
  # 写真利用
  image_picker: ^0.6.7+22

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  stacked: ^1.9.5
  slimy_card: ^1.0.4
  get_it: ^5.0.6
  flutter_spinkit: "^4.1.2"
  flutter_emoji: ^2.2.1+1
  flutter_rating_bar: ^3.2.0+1
  flushbar: ^1.10.4
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - "images/puha-color.png"
